channels:
  - defaults
  - conda-forge

dependencies:
  - cartopy
  - gdal
  - jupyterlab
  - mapclassify
  - poppler
  - rasterio
  - scikit-learn
  - pip
  - python=3.9
  - pip:
    - folium
    - geopandas 
