channels:
  - defaults
  - conda-forge

dependencies:
  - cartopy
  - gdal
  - jupyterlab
  - mapclassify
  - poppler
  - rasterio
  - scikit-learn
  - tqdm
  - pip
  - python=3.9
  - pip:
    - albumentations
    - folium
    - geopandas
    - opencv-python
    - pytorch-lightning
    - rtree
    - slidingwindow
    - xmltodict
